version: '3.8'

services:
  mysql:
    container_name: planner_system
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "planner_system"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Seoul'
    ports:
      - "3308:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
